from typing import Any
def LocalStorageSettings(support_info:bool=True,
                         debugging:bool=False,
                         json_indent:int=4,
                         root_identifier_start:str='$$ROOT$',
                         local_identifier_start:str='$$LOCAL$',
                         metadata_separator_character:str='-'
                         ,metadata_separator_count:int=44,
                         metadata_separator_message:str='END'
                         ,metadata_separator_innerMessage:str='>> START LOCALSTORAGE') -> dict: ...

def load(storage_file_path:str,encoding:str='utf-8')->None:...
def getItem(key:str)->Any|None:...
def setItem(key:str,value:str,encoding:str='utf-8')->None:...
def clear(clearMetadata:bool=False,encoding:str='utf-8')->None:...
def removeItem(key:str)->None:...
def CreateLocalstorageFile(path:str,support_site:str='not found',support_mail:str="not found",identifier:str='not found',encoding:str='utf-8')->str:...
def LocalstorageFileExists(path:str)->str:...

localstorage_writer_version:str
localstorage_file_version:str